### ISSUE TITLE
Unable to parse bibtex file...

### ISSUE THREAD

**Issue by lsfinn** [hesstobi/atom-autocomplete-latex-cite#12]
It appears that the bibtex parser is unable to handle string substitutions: i.e., the entry 

```
@string{ prd = "Phys. Rev. D"}
@Article{	  alexander:2000:bgi,
  author	= "S. Alexander and Robert H. Brandenberger and D. Easson",
  title		= "Brane gases in the early universe",
  journal	= prd,
  volume	= 62,
  pages		= "103509",
  year		= 2000,
}

```
causes the error 

`Unable to parse Bibtex file /Users/lsfinn/Documents/Repositories/git/Research/GWAstro/Manuscript/bib/art.bib. It will be ignored for autocompletion. (Value expected: single_valueprd, volume = 62, pages = "103509", year = 2000, } for key: prd)
`
But, 

```
@Article{	  alexander:2000:bgi,
  author	= "S. Alexander and Robert H. Brandenberger and D. Easson",
  title		= "Brane gases in the early universe",
  journal	= "Phys. Rev. D",
  volume	= 62,
  pages		= "103509",
  year		= 2000,
}

```
parses without problem.

**Comment by hesstobi** [comment]
Fixed in Version v0.3.4
