### ISSUE TITLE
Package does not work with language-latex2e

### ISSUE THREAD

**Issue by werunom** [hesstobi/atom-autocomplete-latex-cite#4]
The autocomplete for citation is not working with the [language-latex2e](https://github.com/Aerijo/language-latex2e) package. But when I disable that and use [language-latex](https://github.com/area/language-latex), then autocomplete works fine.

I have raised the issue in both the places since I couldnt figure out who should provide the fix :) See [here](https://github.com/Aerijo/language-latex2e/issues/7)

**Comment by Aerijo** [comment]
@werunom This is more of an Atom issue. To help optimise load times, etc, packages can define `activationHooks` that trigger package activation. Ideally, there would be one for a grammar scope being used (like `text.tex.latex`), but it currently only works on a per package basis. E.g., the `activationHooks` for this package is `language-latex:grammar-used`. I have no way of getting around this, short of making a PR to every package that has LaTeX grammar based activation hooks.

I'll make a PR to this package now though.

**Comment by werunom** [comment]
That looks like a tedious task - doing the patch for every package. In anycase, thanks for this quick fix. Will wait for the release of this PR.
